### ISSUE TITLE
Pytest works fine locally but fails in GitHub workflows

### ISSUE THREAD

**Issue by standard-librarian** [standard-librarian/Function-Plotter#6]
## Description:
I am encountering an issue with running pytest in GitHub workflows for my project. Locally, pytest runs without any problems, but when running the tests as part of the GitHub workflow, it fails with an import error related to the app.utils package/module.

## Workflow File:
I have a GitHub workflow file that triggers the pytest command as part of the test job. Here is the relevant section of the workflow file:
```yaml
name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tests
      run: |
        tox -e py37
```
Error Message:
When running the pytest command within the GitHub workflow, I receive the following error message:
```bash
ImportError while loading conftest 'D:\a\Function-Plotter\Function-Plotter\tests\conftest.py'.
tests\conftest.py:2: in <module>
    from app.plotter import Plotter
.tox\py37\lib\site-packages\app\plotter.py:11: in <module>
    from app.utils.plot_option import PlotOption
E   ModuleNotFoundError: No module named 'app.utils'
ERROR: InvocationError for command 'D:\a\Function-Plotter\Function-Plotter\.tox\py37\Scripts\pytest.EXE' -m auto (exited with code 4)
```
Additional Information:
- The project is structured as a package, with the `app` package containing the `utils` module.
- Locally, I have successfully installed the package and run the tests using `pytest`.
- I have verified that the `app.utils` module exists and is in the correct location within the project structure.
- The error suggests that the `app.utils` module cannot be found during the pytest execution within the GitHub workflow.

I would greatly appreciate any assistance in resolving this issue and making the pytest command work successfully in the GitHub workflow. Thank you!
